### ISSUE TITLE
How to interpret the data?

### ISSUE THREAD

**Issue by prabinrath** [irapkaist/file_player_mulran#1]
I am interested in using MulRan KAIST03. I have the data but I am unable to interpret it. Specifically, what does global_pose.csv have? what do the 13 columns represent?

**Comment by mhaboali** [comment]
Check the video here: https://www.youtube.com/watch?v=uU-FC-GmHXA

**Comment by streamB** [comment]
The **global_pose.csv** file stores timestamps (1) and corresponding pose matrix (2~13) with size(3, 4). The last row of the matrix is removed since it will always be [0, 0, 0, 1].

**Comment by gisbi-kim** [comment]
Sorry for the late response guys, 
The answer from @streamB is exactly right. Thank you!

I close this issue.
