### ISSUE TITLE
Field "t" in ouster scans

### ISSUE THREAD

**Issue by mramezani64** [irapkaist/file_player_mulran#16]
Hi,
It seems field "t" is not filled in conjunction with the other fields in the ouster scan topic. Is there a way to fix this or it is missing in bin files?

**Comment by minwoo0611** [comment]
Sorry for the late responding.

Actually, there are only channels with x, y, z, intensity. Therefore, the channel "t" is missing in bin files. However, if you need a time channel and the accuracy of time is not really critical, you can assume the uniform circular motion, and propagate the time for each point.

There are some examples such as [CLINS](https://github.com/APRIL-ZJU/clins) and  [FAST-LIO2](https://github.com/hku-mars/FAST_LIO/blob/main/src/preprocess.cpp), which are given the time channel to velodyne. 

I hope that your problem can be solved by this comment.
