### ISSUE TITLE
PCL library error during compile

### ISSUE THREAD

**Issue by ayoungk** [irapkaist/file_player_mulran#17]
Encountered the following compile error
error: #error PCL requires C++14 or above

**Comment by ayoungk** [comment]
Commenting out line 3 from CMakeLists.txt resolved the issue. But I am not sure if this is okay.

#add_definitions(-std=c++11)

**Comment by minwoo0611** [comment]
Hello @ayoungk,

It seems that the compile error you encountered is related to the C++ compiler version. I have observed a similar issue in ROS Noetic, which is associated with Ubuntu 20.04.

To address this compiler version discrepancy, I recommend modifying the [specified line](https://github.com/irapkaist/file_player_mulran/blob/bb3b8a0119bf0efcec1bf3a85b1a86d73ca492be/CMakeLists.txt#L4C1-L4C28) in the CMakeLists.txt. Change `add_definitions(-std=c++11)` to `add_definitions(-std=c++14)`.
