### ISSUE TITLE
What's the extrinsic parameters between the lidar and the imu?

### ISSUE THREAD

**Issue by G4419** [irapkaist/file_player_mulran#27]
Sorry to open this issue here, but I couldn't find the extrinsic parameters on the official website. There is only an extrinsic calibration file between the base and the lidar. Could anyone tell me what the extrinsic parameters is?

**Comment by dongjae0107** [comment]
The authors did not provide the extrinsic data for the IMU and GPS on the official website. However, MulRan used an almost identical sensor system to the Complex Urban Dataset (https://sites.google.com/view/complex-urban-dataset/home), which provides all the extrinsic data. You can obtain the extrinsic parameters between the base and the LiDAR from the MulRan website, and the extrinsic parameters between the base and the IMU/GPS from the Complex Urban Dataset website. With these parameters, you can calculate the extrinsic parameters between the LiDAR and the IMU or GPS.

**Comment by G4419** [comment]
Thanks a lot. I will give it a try.
