### ISSUE TITLE
IMU Data is missing

### ISSUE THREAD

**Issue by mschratter** [irapkaist/file_player_mulran#3]
Thanks a lot for your dataset and the interface to provide the data for the Lio-SAM implementation. 
I tried it out with the KAIST02 and the Riverside03 dataset but in both cases not /imu/data_raw and /gps/fix is published. The point cloud and radar data are transmitted.
In the terminal I get following output:

`SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    file_player (file_player/file_player)

ROS_MASTER_URI=http://localhost:11311

process[file_player-1]: started with pid [6708]
Gtk-Message: 15:52:00.452: GtkDialog mapped without a transient parent. This is discouraged.
Stamp data are loaded
Gps data are loaded
IMU data are loaded

`

Do you have any idea what I could do wrong?

**Comment by gisbi-kim** [comment]
Thank you for having an interest in our dataset.

I recommend to you check the timestamp of data_stamp.csv and xsens_imu.csv are matched.
if you place the other sequence's imu.csv file there (ours have multiple sequences so it can be confusing), it will be successfully loaded but the topic will not flow.
