### ISSUE TITLE
Process has died, exit code -11

### ISSUE THREAD

**Issue by yutouwd** [irapkaist/file_player_mulran#4]
Hello,

I want to play the Mulran dataset. After I load the file and click play, the process would die. The command line output is as followed:

```shell
... logging to /home/yutouwd/.ros/log/84678ea4-69e4-11eb-ac3d-2f3f3c23690a/roslaunch-yutouwd-26449.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://yutouwd:40347/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    file_player (file_player/file_player)

ROS_MASTER_URI=http://localhost:11311

process[file_player-1]: started with pid [26473]
Stamp data are loaded
[file_player-1] process has died [pid 26473, exit code -11, cmd /home/yutouwd/workspace/ScanContext/devel/lib/file_player/file_player __name:=file_player __log:=/home/yutouwd/.ros/log/84678ea4-69e4-11eb-ac3d-2f3f3c23690a/file_player-1.log].
log file: /home/yutouwd/.ros/log/84678ea4-69e4-11eb-ac3d-2f3f3c23690a/file_player-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done


```

I download the KAIST02 sequence and I have made it has the same file structure like the video :https://www.youtube.com/watch?v=uU-FC-GmHXA
```
├── global_pose.csv
└── sensor_data
    ├── data_stamp.csv
    ├── navtech_top_stamp.csv
    ├── Ouster
    ├── ouster_front_stamp.csv
    └── rader
```

Could you give me some instruction to fix the bug? Thanks a lot.

**Comment by gisbi-kim** [comment]
We recently released IMU and GPS data for all sequences.
Would you download (using the same download links) and place those two files under the sensor_data/ ?

**Comment by zgxsin** [comment]
I encountered the same issue using this dataset: https://drive.google.com/drive/folders/1IQZ485H13GcgdsRgEYj0uFF0jlE1j6dW

**Comment by yutouwd** [comment]
@gisbi-kim,

Thanks for your reply. After adding IMU and GPS data under ```sensor_data```, it would not quit.

**Comment by yizhenhui** [comment]
> 

but my topic of points is no data, did you meet this problem
