### ISSUE TITLE
global_pose.csv? 

### ISSUE THREAD

**Issue by cristianrubioa** [irapkaist/file_player_mulran#5]
What do the 13 columns represent?

**Comment by gisbi-kim** [comment]
The 13th is the altitude in UTM coordinate.

ps. 
1: time, 2-13: SE(3)'s first three rows (except the 0,0,0,1), rowwise. 
the xyz (i.e., 5, 9,13 th columns) is in the UTM coordinate.
you can easily find some way on the web to convert UTM <-> (latitude, longitude)

**Comment by cristianrubioa** [comment]
@gisbi-kim Thanks 👍🏼
