### ISSUE TITLE
[file_player-1] process has died

### ISSUE THREAD

**Issue by hongu0603** [irapkaist/file_player_mulran#8]
henry@henry-MS-7A64:~/lidar_ws$ roslaunch file_player file_player.launch 
... logging to /home/henry/.ros/log/6d544fae-ad09-11ec-84ed-2c56dca361ef/roslaunch-henry-MS-7A64-9660.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://henry-MS-7A64:35093/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.17

NODES
  /
    file_player (file_player/file_player)

ROS_MASTER_URI=http://localhost:11311

process[file_player-1]: started with pid [9677]
Please check the file path. The input path is wrong (data_stamp.csv not exist)
[file_player-1] process has finished cleanly
log file: /home/henry/.ros/log/6d544fae-ad09-11ec-84ed-2c56dca361ef/file_player-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
henry@henry-MS-7A64:~/lidar_ws$ roslaunch file_player file_player.launch 
... logging to /home/henry/.ros/log/6d544fae-ad09-11ec-84ed-2c56dca361ef/roslaunch-henry-MS-7A64-9756.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://henry-MS-7A64:35719/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.17

NODES
  /
    file_player (file_player/file_player)

ROS_MASTER_URI=http://localhost:11311

process[file_player-1]: started with pid [9773]
Stamp data are loaded
[file_player-1] process has died [pid 9773, exit code -11, cmd /home/henry/lidar_ws/devel/lib/file_player/file_player __name:=file_player __log:=/home/henry/.ros/log/6d544fae-ad09-11ec-84ed-2c56dca361ef/file_player-1.log].
log file: /home/henry/.ros/log/6d544fae-ad09-11ec-84ed-2c56dca361ef/file_player-1*.log

**Comment by suchetanrs** [comment]
I had the same issue. I switched to an older commit. The one just before IMU + GPS was introduced. It sorted the issue.
